pipeline:
  test:
    image: distroless.dev/alpine-base:latest
    commands:
      - |
        echo "https://alpine.sakamoto.pl/alpine/edge/main
        https://alpine.sakamoto.pl/alpine/edge/community" > /etc/apk/repositories
      - apk add --no-cache cargo build-base
      # test build
      - cargo build
      # unit tests
      - cargo test
